version: '3'
services:
  react-frontend:
    container_name: react-frontned
    build: ./react-frontend
    command: npm start
    ports: [3000:3000]
    links:
      - express-backend
    depends_on: ['express-backend']
  express-backend:
    container_name: express-backend
    build: ./express-backend
    command: node index.js
    ports: [3001:3000]
    links:
      - postgres
    depends_on: ['postgres', 'adminer']
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: SomeExceedinglyLongPassword
  adminer:
    image: adminer
    restart: always
    depends_on: ['postgres']
    ports:
      - 8080:8080